export const currentGameActions = {
  ADD_NEW_GAME: 'CURRENT_GAME_ADD_NEW',
  ADD_INNER: 'CURRENT_GAME_ADD_INNER',
  ADD_PLAYER: 'CURRENT_GAME_ADD_PLAYER',
  END_GAME: 'CURRENT_GAME_END',
  FORCE_END: 'CURRENT_GAME_FORCE_END',
  NATURAL_END: 'CURRENT_GAME_NATURAL_END',
  /**
   * Take the data from a past game and make it the current game
   *
   * __Note:__ This should only ever be done via middle ware.
   *
   * @property
   */
  RESUME_GAME: 'CURRENT_GAME_RESUME',
  /**
   *
   */
  SET_LEAD: 'CURRENT_GAME_SET_LEAD',
  SET_NEW: 'CURRENT_GAME_SET_NEW_GAME',
  SET_SCORE: 'CURRENT_GAME_SET_SCORE',
  SET_TYPE: 'CURRENT_GAME_SET_TYPE',
  RESTART: 'CURRENT_GAME_RESTART_SAME',
  RESTART_CHANGE_PLAYERS: 'CURRENT_GAME_START_SAME_NEW_PLAYERS',
  UPDATE_LEAD: 'CURRENT_GAME_UPDATE_LEAD',
  UPDATE_SCORE: 'CURRENT_GAME_UPDATE_SCORE',
}
